### ISSUE TITLE
Light turns on and off instantly. 

### ISSUE THREAD

**Issue by GGCHades** [FAXES/Spotlight#1]
Error resuming coroutine: client.lua:81: attempt to index a nil value (field "81")
stack traceback:
       client.lua:81: in function <client.lua:70>

We have encountered this error. Newest version of ESX installed correctly. When i start the resource it turns on for a split second the turns off again. Then you have to restart the resource to even get that. Tried to turn the requirement for leo vehicles to false in case that was the issue. Still the same.

**Comment by FAXES** [comment]
Resolved in new update.
