### ISSUE TITLE
Sync problems

### ISSUE THREAD

**Issue by Guy293** [FAXES/Spotlight#2]
I didn't try the script but by looking at it i can see that you can fix the sync by ignoring light position from the server from only your car.
I can fix it and do a pull request if you want.

In this table include the player id
https://github.com/FAXES/Spotlight/blob/b36b939cad5d458eb5c4bb4381189bc5c078f133/server.lua#L11

And here ignore if it's him
https://github.com/FAXES/Spotlight/blob/b36b939cad5d458eb5c4bb4381189bc5c078f133/client.lua#L34

**Comment by PERPGamer** [comment]
Could you do a pull? So the rest of us who have no idea how to do any of this has something to test to see if it fixes our problem?

**Comment by Guy293** [comment]
Sure this week on next week i will have some time to do it.
Do you have any servers for testing or i need to open my own?

**Comment by Guy293** [comment]
We can also jump into a discord call

**Comment by FAXES** [comment]
Sounds great!

**Comment by Guy293** [comment]
I sent you a messege on discord about a hour ago

**Comment by PERPGamer** [comment]
I have a server if you guys need a server with a good amount of players (22 player when writing this)

**Comment by PERPGamer** [comment]
Any updates on this?

**Comment by Guy293** [comment]
> Any updates on this?

Can you contact me on discord?
Guy293#9782

**Comment by FAXES** [comment]
Updated.
